### ISSUE TITLE
dangling symlinks cause crash

### ISSUE THREAD

**Issue by wimglenn** [cpburnz/python-path-specification#22]
When using `PathSpec.match_tree`, If there is a broken symlink encountered, we get unhandled exception. It's here:

https://github.com/cpburnz/python-path-specification/blob/da86e2c4d557df2d0a7cc9743268a7173d3a4828/pathspec/util.py#L68

I think you could fix it with `os.lstat` instead, but that's backwards incompat change.

Perhaps `iter_tree` could have an option to not follow symlinks? You could follow the example of `os.walk`, which accepts a `followlinks` keyword arg, and also an `onerror` callback which can be used to handle problems such as permission errors when stat each file.

**Comment by cpburnz** [comment]
I've updated `iter_tree` to behave similar to `os.walk` but not identically. Dangling symlinks will now be ignored by default. I've added similar arguments:

-  `on_error`: behaves the same as `os.walk`.
- `follow_links`: default is `True` instead of `os.walk`'s `False` to maintain backwards compatibility of following links.
